---
title: "Inoculations - Quantification - Linear Regressions"
author: "Clarisse Gotti"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: default
  pdf_document: default
---


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(RColorBrewer)
library(janitor)
library(data.table)
library(scales)
```

&nbsp;   
&nbsp;  



```{r}
# Import informations on inoculations
tab <- read.csv("R_Input/Spikes_Infos.txt", sep = "\t", dec = ",") %>%
  mutate(bact_Spike = paste(bact, Spike, sep = "_"))

# Import data
files <- list.files(path = "Skyline/ExportSkyline/", pattern = "ExportSkyline.csv", full.names = T)

# Data
dat <- lapply(files, fread, sep = ";", dec = ",")  

# Calculate median intensity of CytoC
CytoC_dat = CytoC_med = list()

for(i in 1:length(dat)) {

# CytoC    
  CytoC_dat[[i]] <- dat[[i]] %>%
    rename_with(., ~ gsub(" ", ".", .)) %>%
    filter(!grepl("Pool", Replicate.Name) & Protein.Name == "CytoC" & Transition.Note == "x") %>%
    spread(Replicate.Name, Area) %>%
    mutate_if(is.numeric, ~ na_if(., 0))  
  
# Calculate the mediane for all column
  CytoC_med[[i]] <- apply(CytoC_dat[[i]][7:ncol(CytoC_dat[[i]])] , 2, function(x) {median(x, na.rm = T)})  %>%
    as.data.frame 
}

# Median intensity of CytoC over the 360 samples
CytoC_med_all <- do.call(rbind.data.frame, CytoC_med) %>% as.data.frame %>% dplyr::summarise(Med = median(.)) %>% pull

# Normalize bacteria intensity  
Spike_dat = Spike_dat_norm = factor_norm = list()

for(i in 1:length(dat)) {

# Spikes - Quantification based on a single transition
  Spike_dat[[i]] <- dat[[i]] %>%
    rename_with(., ~ gsub(" ", ".", .)) %>%
    filter(!grepl("Pool", Replicate.Name) & Protein.Name != "CytoC" & Transition.Note == "x") %>%
    spread(Replicate.Name, Area) %>%
    mutate_if(is.numeric, ~ na_if(., 0))

# Calculate the normalization factor MEDIANE
  factor_norm[[i]] <- ( CytoC_med[[i]] / CytoC_med_all) %>% pull

# Normalization by normalization factor MEDIANE
  Spike_dat_norm[[i]] <- Spike_dat[[i]]
  Spike_dat_norm[[i]][7:ncol(Spike_dat_norm[[i]])] <- t(apply(Spike_dat[[i]][7:ncol(Spike_dat[[i]])], 1, "/", factor_norm[[i]]))
  Spike_dat_norm[[i]] <- Spike_dat_norm[[i]] %>%
    dplyr::select(-c(Protein.Name, Precursor.Mz, Product.Mz, Fragment.Ion, Transition.Note)) %>%
    gather(Spl, Int, -Peptide.Sequence) %>%
    na.omit %>% as.data.frame
  
}  

# Combine in a single df
quant <- do.call(rbind.data.frame, Spike_dat_norm) %>%
  mutate(Spike = str_extract(Spl, "S[0-6]") %>% factor(., levels = rev(unique(.))), 
         Bacteria = str_extract(Spl, "Eco|Cfr|Kae|Ecl|Kox|Kpn|Efa|Sag|Pae|Sau|Pmi|Smi|Sep|Ssa|Sha"),
         Bact_spike = paste(Bacteria, Spike, sep = "_"),
         Bact_pep = paste(Bacteria, Peptide.Sequence, sep = "_"),
         Concentration = tab$concentration[match(Bact_spike, tab$bact_Spike)]) %>%
  group_by(Bact_spike, Bact_pep, Bacteria, Spike, Peptide.Sequence) %>%
  dplyr::summarise(count = n(),
                   Area = mean(Int), 
                   sd = sd(Int),
                   Conc = mean(Concentration))   %>%
  as.data.frame %>%
  mutate(CV = sd / Area * 100, 
         logArea = log2(Area), 
         logConc = log10(Conc))

## Linear regression - Log data ---------------------------------------------------------
tmp = list()
reg_fun = list()
reg = list()


for(i in 1:length(unique(quant$Bact_pep))) {
    
    tmp[[i]] <- quant %>%
    filter(Bact_pep == unique(Bact_pep)[i]) 
    
  # fit linear regression model using 'x' as predictor and 'y' as response variable
  reg_fun[[i]] <- lm(formula =  tmp[[i]]$logConc  ~ tmp[[i]]$logArea  ) 
  reg[[i]] <- matrix() %>% as.data.frame %>%
    mutate(Exp = unique(quant$Bact_pep)[i],
           slope = round(coef(reg_fun[[i]])[2], 3),
           intercept = round(coef(reg_fun[[i]])[1], 3), 
           R2 = round(as.numeric(summary(reg_fun[[i]])[8]), 3),
           R2.Adj = round(as.numeric(summary(reg_fun[[i]])[9]), 3), 
           NbPoint = sum(tmp[[i]]$count))

}

# Export Quant data
write.table(quant, "R_Output/Spikes_Quant_Data_AllBact_AllPept.txt", sep = "\t", row.names = F)

# Combine regression data in a single df
reg2 <- do.call(rbind.data.frame, reg) %>%
  dplyr::select(-V1) %>%
  separate(Exp, c("Bacteria", "Peptide.Sequence"), sep = "_") %>% 
  mutate(bact_pep = paste(Bacteria, Peptide.Sequence, sep = "_"), 
         Area_S6 = quant_S6$Area[match(bact_pep, quant_S6$Bact_pep)])
write.table(reg2, "R_Output/Spikes_Regressions_Data_AllBact_AllPept.txt", sep = "\t", row.names = F)

```

&nbsp;
&nbsp;

**3 peptides per bacteria - Regressions calculated based on Log areas**          

```{r fig.height = 4, fig.width = 3}

# Peptide to keep for quant
tab2 <- read.csv("R_Input/Quant_Regressions_Data.txt", sep = "\t")

# Add columns in quant df and reg2 df to have peptide for quant
quant2_filt <- quant %>%
  mutate(Pep_for_Quant = ifelse(Bact_pep %in% tab2$Bact_Pep, "Used for quantification", "")) %>%
    filter(Pep_for_Quant == "Used for quantification")
reg2_filt <- reg2 %>%
  mutate(Pep_for_Quant = ifelse(bact_pep %in% tab2$Bact_Pep, "Used for quantification", "")) %>%
    filter(Pep_for_Quant == "Used for quantification")

# Change color order
bact_col2 <- bact_col %>% arrange(Abbreviation) 
colnames(bact_col) <- c("Bacteria2", "Bacteria", "Color")

# Plot 3 peptides / bact
ggplot(quant2_filt, aes(Conc, Area, group = Bact_pep)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = Area - sd, ymax = Area + sd), width = 0.3) + 
  geom_smooth(method = "lm", formula = "y ~ x", se = F) +
  scale_x_continuous(trans = "log2", name = "Bacteria concentration", labels = scientific) +
  scale_y_continuous(trans = "log10", name = "Area") +
  facet_wrap(. ~ Bacteria, ncol = 5) +
  theme_minimal() +
  theme(panel.border = element_rect(color = 'black', fill = NA),
        legend.title = element_blank(),
        legend.position = "none", 
        axis.text.x = element_text(angle = 90, hjust =1, vjust = 0.25))

```


&nbsp;
&nbsp;

**Pearson correlation**            

```{r fig.height = 6, fig.width = 6}
  
# Quant values for Pearson
pear <- do.call(rbind.data.frame, Spike_dat_norm) %>%
  mutate(Spike = str_extract(Spl, "S[0-6]") %>% factor(., levels = rev(unique(.))), 
         Bacteria = str_extract(Spl, "Eco|Cfr|Kae|Ecl|Kox|Kpn|Efa|Sag|Pae|Sau|Pmi|Smi|Sep|Ssa|Sha"),
         Bact_spike = paste(Bacteria, Spike, sep = "_"),
         Bact_pep = paste(Bacteria, Peptide.Sequence, sep = "_"),
         Concentration = tab$concentration[match(Bact_spike, tab$bact_Spike)]) %>%
  mutate(logArea = log2(Int), 
         logConc = log10(Concentration)) %>%
  filter(Bact_pep %in% tab2$Bact_Pep)

# Prepare empty df  
pearson_r <- data.frame(Bact_pep = rep(NA, 45), 
                        Pearson_r = rep(NA, 45))

# Per peptide 
for(i in 1:length(unique(pear$Bact_pep))) {

x <- pear %>%
  filter(Bact_pep == unique(pear$Bact_pep)[i] ) 
val <- cor(x$logConc, x$logArea, method = "pearson")

pearson_r$Bact_pep[i] = unique(pear$Bact_pep)[i]
pearson_r$Pearson_r[i] <- round(val, 3)

}

# Export data
write.table(pearson_r, "R_Output/Spikes_Pearson_Coeff.txt", sep = "\t", row.names = F)


```
