---
title: "Quantification of unknown samples"
author: "Clarisse Gotti"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: default
  pdf_document: default
---


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(RColorBrewer)
library(janitor)
library(data.table)
library(scales)
library(cowplot)
```

&nbsp;   
&nbsp;  

## Quantification 

```{r fig.height = 6, fig.width = 8}
# Load data
dat <- read.csv("R_Input/Export_Skyline.csv", sep = ";", dec = ",")
colnames(dat) <- gsub(" ", ".", colnames(dat))

# CytoC    
CytoC_dat <- dat %>%
  filter(Protein.Name == "CytoC" & Transition.Note == "x") %>%
  mutate(Area = gsub("#N/A", NA, Area) %>% as.numeric)  %>%
  spread(Replicate.Name, Area)

# Calculate the mediane for all column
CytoC_med <- data.frame(Med_CytoC = apply(CytoC_dat[7:ncol(CytoC_dat)] , 2, function(x) {median(x, na.rm = T)}) ) %>%
  mutate(Med_CytoC_log = log2(Med_CytoC))

# Spikes - Quantification based on a single transition
Spike_dat <- dat %>%
  filter(Protein.Name != "CytoC" & Transition.Note == "x") %>%
    mutate(Area = gsub("#N/A", NA, Area) %>% as.numeric)  %>%
  spread(Replicate.Name, Area)


# Median intensity of CytoC over the 360 samples
CytoC_med_all <- CytoC_med %>% dplyr::summarise(Med = median(Med_CytoC)) %>% pull

# Calculate the normalization factor MEDIANE
factor_norm <- CytoC_med$Med_CytoC / 1050641.7

# Normalization 
Spike_dat_norm <- Spike_dat
Spike_dat_norm[7:ncol(Spike_dat_norm)] <- t(apply(Spike_dat[7:ncol(Spike_dat)], 1, "/", factor_norm))
Spike_dat_norm <- Spike_dat_norm %>%
  dplyr::select(-c(Protein.Name, Precursor.Mz, Product.Mz, Fragment.Ion, Transition.Note)) %>%
  gather(Spl, Int, -Peptide.Sequence) %>%
  na.omit %>% as.data.frame
  
# Import ML prediction
tab <- read.csv("R_Input/Spl_Infos.txt", sep = "\t", dec = ",")

# Import regressions for 3 peptides to quant the bacteria
reg <- read.csv("R_Input/Quant_Regressions_Data.txt", sep = "\t")

# Quantification
quant <- Spike_dat_norm %>%
  cbind(., tab[match(.$Spl, tab$Urine),]) %>%
  mutate(Bact_pep = paste(predicted, Peptide.Sequence, sep = "_")) %>%
  filter(Bact_pep %in% reg$bact_pep) %>%
  cbind(., reg[match(.$Bact_pep, reg$bact_pep), c("slope", "intercept")]) %>%
  mutate(Conc = (Int - intercept) / slope)

write.table(quant, "R_Output/Quantification.txt", sep = "\t", row.names = F)

```

